### ISSUE TITLE
Android Facebook plugin not working

### ISSUE THREAD

**Issue by Saurav-K-Aryal** [Saurav-K-Aryal/huevents#1]
After following all the steps listed on the demo repo for Android login, I am still having issues like facebookConnectPlugin is not defined. Any help will be appreciated, I searched and tried various fixes suggested online on stackoverflow,ionicframework forums, and gits of ngCordova. None of the suggested fixes have worked for me.

Please help @aaronksaunders.

**Comment by aaronksaunders** [comment]
Also I specifically said if you had and issue to document the steps you followed and the error log information if you wanted assistance? I do see either of those done here

Move on, don't let this be a blocker. 

Your app should work without Facebook login. Then Facebook login should be an additional feature.

**Comment by Saurav-K-Aryal** [comment]
@aaronksaunders and @PrekshaK I just pushed a commit with android login working and we also get User data on Parse now. Can you direct me towards how we can handle image uploading to Parse? I want to be able to pick images from my filesystem and the camera plugin will be a feature.

**Comment by PrekshaK** [comment]
http://www.clearlyinnovative.com/ionic-framework-camera-image-uploads-and-base64-strings

this is probably the one. I will be looking into this link.

**Comment by aaronksaunders** [comment]
@PrekshaK I have updated the github example, please review the readme - https://github.com/aaronksaunders/Ionic-CameraTest6Plus
